# Generated by Django 5.0.2 on 2024-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='custommer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
